### ISSUE TITLE
Support for NX 12?

### ISSUE THREAD

**Issue by iangregsondev** [JacopoPatroclo/nx-react-native-expo#14]
Is this planned ?

**Comment by JacopoPatroclo** [comment]
No but it could. I need to check which changes are needed and start working on it. Do you have some resources or some errors to share? That would help me on this process.

**Comment by iangregsondev** [comment]
Hi @JacopoPatroclo, Thanks for the quick response.

I actually didn't try it :-) I assumed it needed upgrading, anyway, I tried it now.

Here are my findings and some questions.

It seems to run perfectly :-)

Although it creates a project with a lower sdk for expo, but this was fixed easier enough by running

```
expo upgrade
```

I ran it in the root, I presume this is correct? Or I should run it under ./apps/myapp ?

It seemed to work :-)

I noticed if i want to use the EXPO command directly (not upgrade, as that works :-) ) then i should run it under ./apps/myapp 

OR 

expo [cmd] ./apps/myapp..

Its looking good though, maybe just release a new version to use the latest libraries ?

**Comment by iangregsondev** [comment]
Oh, there is a typo, but nothing major - on the README

```
yarn -D nx-react-native-expo
```

should be

```
yarn add -D nx-react-native-expo
```

Maybe some comments about how you would Eject, i presume this is still possible, or it just would work - i assume - again i haven't tried it.

**Comment by iquabius** [comment]
I ran into an issue after upgrading `@nrwl/*` packages and running `npx nx run myapp:start`: `Cannot find module '@angular-devkit/core'`

<details>
<summary>Expand to see full error output</summary>
  
```sh
➜ npx nx run myapp:start --verbose                                                                    

> nx run myapp:start --verbose 
Cannot find module '@angular-devkit/core'
Require stack:
- /home/iqb/Code/Sogni/zaula/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /home/iqb/Code/Sogni/zaula/node_modules/@nrwl/tao/src/commands/run.js
- /home/iqb/Code/Sogni/zaula/node_modules/@nrwl/tao/index.js
- /home/iqb/Code/Sogni/zaula/node_modules/@nrwl/cli/lib/run-cli.js
Error: Cannot find module '@angular-devkit/core'
Require stack:
- /home/iqb/Code/Sogni/zaula/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /home/iqb/Code/Sogni/zaula/node_modules/@nrwl/tao/src/commands/run.js
- /home/iqb/Code/Sogni/zaula/node_modules/@nrwl/tao/index.js
- /home/iqb/Code/Sogni/zaula/node_modules/@nrwl/cli/lib/run-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.require (/home/iqb/Code/Sogni/zaula/node_modules/@nrwl/tao/src/compat/compat.js:7:40)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/iqb/Code/Sogni/zaula/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)

———————————————————————————————————————————————

>  NX   ERROR  Running target "myapp:start" failed

  Failed tasks:

  - myapp:start
```
</details>


Updating to these versions:

![image](https://user-images.githubusercontent.com/3139777/128090890-5007dfef-b6c3-4fb0-b302-28cf8cfaca81.png)

How I fixed it:

```sh
npm remove nx-react-native-expo
npm i -D nx-react-native-expo@latest
```
