### ISSUE TITLE
App creation fails on Nx13

### ISSUE THREAD

**Issue by mwoodpatrick** [JacopoPatroclo/nx-react-native-expo#24]
If I run the following commands:

```
  npx create-nx-workspace westie-expo --packageManager=yarn --cli=nx --preset=empty
  cd westie-expo/
  yarn add -D nx-react-native-expo
  npx nx g nx-react-native-expo:app exptest
```

I get:

```
npx nx g nx-react-native-expo:app exptest
TypeError: Cannot set properties of undefined (setting 'exptest')
    at /mnt/wsl/projects/git/www/westie-expo/node_modules/nx-react-native-expo/src/schematics/application/application.impl.js:45:44
    at /mnt/wsl/projects/git/www/westie-expo/node_modules/@nrwl/workspace/src/utils/ast-utils.js:310:53
    at MergeMapSubscriber.project (/mnt/wsl/projects/git/www/westie-expo/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/mnt/wsl/projects/git/www/westie-expo/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/mnt/wsl/projects/git/www/westie-expo/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/mnt/wsl/projects/git/www/westie-expo/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/mnt/wsl/projects/git/www/westie-expo/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/mnt/wsl/projects/git/www/westie-expo/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/mnt/wsl/projects/git/www/westie-expo/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TapSubscriber._next (/mnt/wsl/projects/git/www/westie-expo/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/tap.js:65:26)
Cannot set properties of undefined (setting 'exptest')
```

**Comment by charlesmarkovich** [comment]
Same issue happening to me as well.

**Comment by algoflows** [comment]
Same for me..... can't seem to install this

**Comment by algoflows** [comment]
Is this app still being supported, no comments from the maintainer since this issue was raised over a month ago...?!

**Comment by JacopoPatroclo** [comment]
@JuniorDEVed the code is there if u want to help. I'm struggling with the maintenance of this project due to personal and work stuff. The rewriting to support nx 12-13 is in progress. There is an branch with some work done but is not working at this time.

**Comment by algoflows** [comment]
Hey buddy, I am a little too junior for it :) will gladly contribute once my skills improve.

**Comment by Archisman-Mridha** [comment]
I am also having same issue
