### ISSUE TITLE
Error during npx nx g nx-react-native-expo:app

### ISSUE THREAD

**Issue by npwork** [JacopoPatroclo/nx-react-native-expo#6]
Node: v15.5.0
OS: Mac OS 11.1 (20C69)
"nx-react-native-expo": "0.0.8",
NPM: 6.14.11

Following instructions from "Get started":
* create empty NX workspace
* add nx-react-native-expo plugin

When I run `npx nx g nx-react-native-expo:app mobile`

I get this error:
```code
alex@Alexs-MacBook-Pro sv % npx nx g nx-react-native-expo:app mobile
TypeError: ignore_1.default is not a function
    at /Users/alex/Work/tmp/nx/sv/node_modules/nx-react-native-expo/src/schematics/init/init.impl.js:65:36
    at MergeMapSubscriber.project (/Users/alex/Work/tmp/nx/sv/node_modules/nx-react-native-expo/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/Users/alex/Work/tmp/nx/sv/node_modules/nx-react-native-expo/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/alex/Work/tmp/nx/sv/node_modules/nx-react-native-expo/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/alex/Work/tmp/nx/sv/node_modules/nx-react-native-expo/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/alex/Work/tmp/nx/sv/node_modules/nx-react-native-expo/node_modules/rxjs/internal/operators/mergeMap.js:95:26)
    at InnerSubscriber._next (/Users/alex/Work/tmp/nx/sv/node_modules/nx-react-native-expo/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/alex/Work/tmp/nx/sv/node_modules/nx-react-native-expo/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/alex/Work/tmp/nx/sv/node_modules/nx-react-native-expo/node_modules/rxjs/internal/operators/mergeMap.js:95:26)
    at InnerSubscriber._next (/Users/alex/Work/tmp/nx/sv/node_modules/nx-react-native-expo/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
ignore_1.default is not a function
```

**Comment by npwork** [comment]
After updating global package
"@nrwl/cli": "11.1.1",
it worked.

**Comment by AlexJWayne** [comment]
I got this too, and needed to `npm install --save-dev ignore`
