### ISSUE TITLE
support for pnpm and pnpx

### ISSUE THREAD

**Issue by seyaobey** [JacopoPatroclo/nx-react-native-expo#8]
I'm wondering whether this (excellent) plugin supports also `pnpm`

I have created a nx workspace with `pnpm, pnpx` as packages manager following [this announcement stating nx supports pnpm](https://blog.nrwl.io/cleaner-eslint-config-and-pnpm-compatibility-with-nx-10-4-3f6faa3cdd19).

But after I've started metro bundler, with `pnpx nx start <app-name>` I get this error:

```
Error: ENOENT: no such file or directory, open 'fs.js'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
```
Even if I use `npx nx start <app-name>`

Thanks for the great work!

**Comment by JacopoPatroclo** [comment]
This project is not maintained by the nx team so the package currently don't have support for pnpm. I'll use this issue to track the development of this feature.

Unfortunately I'm the only maintainer and during this period I've no time to dedicate to this project. If someone wants to give me a hand on this it will be very much appreciated.

**Comment by seyaobey** [comment]
@JacopoPatroclo thanks for reply. I'll just be patient. (I'm far from having the skills to overtake this project, but I'll try to have a look).

**Comment by leggomuhgreggo** [comment]
_For anyone who is interested, I wanted to share some findings/context from my investigation._

### Context
If you find yourself in this repo, it's probably fairly evident that getting RN / Expo projects to work within a monorepo is uniquely challenging. Generally, this stems from module resolution API disparity between node packagers and the metro bundler. _(But also, shoutout to unexpected caching issues -- the next most encumbering issue with RN/Expo dev)_ 

### Packaging with pnpm
The module resolution issues are particularly challenging when using `pnpm`, because metro doesn't currently play nicely with symlinked node_modules. This issue has gotten some attention over in the [pnpm repo](https://github.com/pnpm/pnpm/issues/3010) and, with thanks to vjpr, there's a [working example](https://github.com/vjpr/pnpm-expo-example/tree/main/packages/pnpm-expo-helper) of how to adapt the metro config to support pnpm symlinks

### Possible course of action
This repo includes a [`withNxMetro` plugin](https://github.com/JacopoPatroclo/nx-react-native-expo/blob/master/packages/react-native-expo/plugins/with-nx-metro.ts), which could be adapted (or perhaps more sensibly branched?) to support the pnpm module resolution features from the [pnpm-expo-helper's](https://github.com/vjpr/pnpm-expo-example) [`rn-cli-config`](https://github.com/vjpr/pnpm-expo-example/blob/main/packages/pnpm-expo-helper/rn-cli.config.js)

I would love to work on this but pnpm support isn't an immediate priority for my project -- but I hope this helpful in advancing the topic.

And big ole thanks to Jacopo for this repo -- made some very cool things possible in my world 🙏

**Comment by violabg** [comment]
I'm getting the same error when using yarn nx start <app-name>

```
Error: ENOENT: no such file or directory, open 'fs.js'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
```
